# Generated by Django 4.1.4 on 2022-12-13 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('picture', models.JSONField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('word_guessed', models.CharField(max_length=20, null=True)),
                ('guessed_right', models.BooleanField(default=False)),
                ('drawing_guessed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_guessed', to='game.drawing')),
                ('drawing_made', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_made', to='game.drawing')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_session', to='game.session')),
            ],
        ),
    ]
