# Generated by Django 4.1.4 on 2022-12-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_drawing_word_session_timestamp_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='available_words',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
