# Generated by Django 4.1.4 on 2022-12-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_session_available_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='available_words',
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
