# Generated by Django 4.1.4 on 2022-12-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
